### ISSUE TITLE
Missing debian-9.2.1-x86 image.

### ISSUE THREAD

**Issue by blu3sh0rk** [SQLab/CRAXplusplus#13]
Hello,
After entering command `s2e image_build linux`,the terminal display:
`INFO: [image_build] The following images will be built:
INFO: [image_build]  * ubuntu-22.04-x86_64
INFO: [image_build]  * debian-11.3-i386
INFO: [image_build]  * cgc_debian-9.2.1-i386
INFO: [image_build]  * debian-11.3-x86_64`
Missing the debian-9.2.1-x86 image,how do i download this image to complete the next steps?

Thanks!

**Comment by aesophor** [comment]
Hi there! Thanks for trying out our AEG.

Can you please try to clone `s2e-env` again and see if it works? Here are the commands I executed:
```
cd ~/s2e/source
mv s2e-env s2e-env.old
git clone https://github.com/s2e/s2e-env.git

cd s2e-env
python3 -m venv venv
. venv/bin/activate
pip install --upgrade pip
pip install .

cd ~/s2e
source s2e_activate
```

After that, download the images. I did this with `-d` flag, and `debian-9.2.1-x86_64` shows up.
```
> s2e image_build linux -d
INFO: [image_build] The following images will be built:
INFO: [image_build]  * debian-9.2.1-x86_64
INFO: [image_build]  * debian-9.2.1-i386
INFO: [image_build]  * cgc_debian-9.2.1-i386
INFO: [s2e_env.utils.images] Downloading https://drive.google.com/open?id=1fybAk4Qb-0Ig8W3immpwBLc-SZoN7UUh
INFO: [s2e_env.utils.google] Requesting https://docs.google.com/uc?export=download with id=['1fybAk4Qb-0Ig8W3immpwBLc-SZoN7UUh']
INFO: [s2e_env.utils.google] File size: 1183768760 bytes
|█████████████████▋                      | ▆▄▂ 519831552/1183768760 [44%] in 11s (45664657.9/s, eta: 15s)
```

Let me know if this helps, thanks.

**Comment by blu3sh0rk** [comment]
Thanks for the solution, I've been able to download `debian-9.2.1-x86_64`， thanks again!

**Comment by LucasLeeNDS** [comment]
Sorry I just misread, after I redownloaded s2e-env, I used `s2e image_build linux -d `and it still shows：
`
>s2e image_build linux -d
INFO: [image_build] The following images will be built:
INFO: [image_build]  * debian-11.3-i386
INFO: [image_build]  * debian-11.3-x86_64
INFO: [image_build]  * ubuntu-22.04-x86_64
INFO: [image_build]  * cgc_debian-9.2.1-i386
INFO: [s2e_env.utils.images] Downloading https://drive.google.com/open?id=1fNw4Vfa2Z3neZGZvMIIQ38q06PuNvARS
INFO: [s2e_env.utils.google] Requesting https://docs.google.com/uc?export=download with id=['1fNw4Vfa2Z3neZGZvMIIQ38q06PuNvARS']
INFO: [s2e_env.utils.google] File size: 1732873140 bytes
|▏⚠︎                                      | (!) 5373952/1732873140 [0%] in 51.6s (104181.09/s)

`

Could it be that the s2e project has an update?

**Comment by blu3sh0rk** [comment]
Sorry I just misread, after I redownloaded `s2e-env`, I used `s2e image_build linux -d` and it still shows：

```
>s2e image_build linux -d
INFO: [image_build] The following images will be built:
INFO: [image_build] * debian-11.3-i386
INFO: [image_build] * debian-11.3-x86_64
INFO: [image_build] * ubuntu-22.04-x86_64
INFO: [image_build] * cgc_debian-9.2.1-i386
INFO: [s2e_env.utils.images] Downloading https://drive.google.com/open?id=1fNw4Vfa2Z3neZGZvMIIQ38q06PuNvARS
INFO: [s2e_env.utils.google] Requesting https://docs.google.com/uc?export=download with id=['1fNw4Vfa2Z3neZGZvMIIQ38q06PuNvARS']
INFO: [s2e_env.utils.google] File size: 1732873140 bytes
|▏⚠︎ | (!) 5373952/1732873140 [0%] in 51.6s (104181.09/s)
```
Could it be that the s2e project has an update?

**Comment by aesophor** [comment]
Maybe this will work? [ref](http://s2e.systems/docs/s2e-env.html#building-an-image)

```
> s2e image_build debian-9.2.1-x86_64 -d
INFO: [image_build] The following images will be built:
INFO: [image_build]  * debian-9.2.1-x86_64
INFO: [s2e_env.utils.images] Downloading https://drive.google.com/open?id=1fybAk4Qb-0Ig8W3immpwBLc-SZoN7UUh
INFO: [s2e_env.utils.google] Requesting https://docs.google.com/uc?export=download with id=['1fybAk4Qb-0Ig8W3immpwBLc-SZoN7UUh']
INFO: [s2e_env.utils.google] File size: 1183768760 bytes
|██████▉                                 | ▂▄▆ 202768384/1183768760 [17%] in 2s (81784154.5/s, eta: 12s)
```

**Comment by blu3sh0rk** [comment]
It doesn't work.
```
>s2e image_build debian-9.2.1-x86_64 -d
ERROR: [image_build] debian-9.2.1-x86_64 does not exist

```

**Comment by aesophor** [comment]
Hmm… weird. I would suggest that you ask Vitaly (the lead developer of S2E) here: https://groups.google.com/g/s2e-dev

**Comment by blu3sh0rk** [comment]
Thanks, I found the url of the image from your record, I'll try to download it in Google Cloud Drive, sorry to bother you.

**Comment by aesophor** [comment]
~Btw you can also cd into \~/s2e/source/s2e and checkout to this commit: https://github.com/S2E/s2e/commit/002a0eed234a50f68ef08be5ea8e7c551650693c~

**Comment by aesophor** [comment]
Hey i think i've found the problem. It's due to ~/s2e/source/guest-images

```
cd ~/s2e/source/guest-images
git checkout 2afd9e4
s2e image_build debian-9.2.1-x86_64 -d
```

This will work.

**Comment by blu3sh0rk** [comment]
Now available for download, thanks!
