### ISSUE TITLE
./launch-crax.sh 

### ISSUE THREAD

**Issue by siruiTT** [SQLab/CRAXplusplus#18]
Does this require a qemu version change? Am I just one step away from successDoes this require a qemu version change? Am I just one step away from success?
please !thk!

ting module: DynamicRop
CRAX: Creating technique: Ret2csu
CRAX: Creating technique: BasicStackPivoting
CRAX: Creating technique: Ret2syscall
Initializing MemUtils
Initializing FunctionModels
Initializing ModuleExecutionDetector
Initializing CUPASearcher
CUPASearcher: CUPASearcher is now active
Initializing TranslationBlockCoverage
Initializing ModuleTracer
Initializing CorePlugin
[Z3] Initializing
2 [State 0] Created initial state
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.40000001H:EAX.kvm-nopiodelay [bit 1]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.40000001H:EAX.kvmclock [bit 3]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.40000001H:EAX.kvm-asyncpf [bit 4]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.40000001H:EAX.kvm-steal-time [bit 5]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.40000001H:EAX.kvm-pv-eoi [bit 6]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.40000001H:EAX.kvmclock-stable-bit [bit 24]
Adding CPU (addr = 0x7fa65c00a760, size = 0x36ea0)
qemu-system-x86_64: warning: hub 0 is not connected to host network
Modification timestamp of 'json:{"driver": "s2e"}' changed since the creation of the snapshot 'ready' (st_mtime 1669361554 != 1658661755).
Please recreate a new snapshot.
qemu-system-x86_64: Could not load snapshot 'ready' on 'ide0-hd0': Failed to load snapshot: Operation not permitted
Does this require a qemu version change? Am I just one step away from success?

**Comment by aesophor** [comment]
This means that you've modified the timestamp of your S2E image. The image consists of three files:
* image.json
* image.raw.s2e
* image.raw.s2e.ready

S2E will refuse to start if the last modification timestamps of these three files have been changed since you download them with `s2e image_build linux -d`.
```
Modification timestamp of 'json:{"driver": "s2e"}' changed since the creation of the snapshot 'ready' (st_mtime 1669361554 != 1658661755).
```

The simplest way to fix this is to redownload the s2e image with
```
s2e image_build linux -d
```

Or if you know the timestamp, you can restore the "last modified timestamp" of these three files.
```
touch --date=@1577029235 image.json image.raw.s2e image.raw.s2e.ready
```
